# Generated by Django 5.0.1 on 2025-04-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_opals_question10_opals_question11_opals_question12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opals',
            name='question13',
            field=models.CharField(blank=True, choices=[('level131', 'No patch(es) of shade.'), ('level132', 'Patch(es) of shade sufficient for a few children.'), ('level133', 'Patch(es) of shade sufficient for most children.'), ('level134', 'Patch(es) of shade sufficient for all children.')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question14',
            field=models.CharField(blank=True, choices=[('level141', 'As calculated by formula, 0% to 29% sufficient trees.'), ('level142', 'As calculated by formula, 30% to 64% sufficient trees.'), ('level143', 'As calculated by formula, 65% to 99% sufficient trees.'), ('level144', 'As calculated by formula, 100% or more of sufficient trees.')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question15',
            field=models.CharField(blank=True, choices=[('level141', 'As calculated by formula, 0% to 29% sufficient trees.'), ('level142', 'As calculated by formula, 30% to 64% sufficient trees.'), ('level143', 'As calculated by formula, 65% to 99% sufficient trees.'), ('level144', 'As calculated by formula, 100% or more of sufficient trees.')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question16',
            field=models.CharField(blank=True, choices=[('level161', 'No fruit or vegetables garden.'), ('level162', 'There is a vegetable or fruit garden with limited produce to taste or use for snacks/ meals.'), ('level163', 'There is a fruit and vegetable garden with enough produce for some of the children to taste or use for snacks/meals.'), ('level164', 'There is a fruit and vegetable garden with abundant produce for all children to taste or use for snacks/meals.'), ('level165', 'N/A')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question17',
            field=models.CharField(blank=True, choices=[('level171', 'There is no outdoor storage'), ('level172', 'There are open storage containers (e.g. crates, open boxes'), ('level173', 'There is at least one enclosed closet or chest or sheltered outdoor shelving.'), ('level174', 'There is more than one enclosed closet or chest or sheltered outdoor shelving.'), ('level175', 'N/A')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opals',
            name='state',
            field=models.CharField(choices=[('', 'State'), ('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=100),
        ),
    ]
