# Generated by Django 5.0.1 on 2025-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_opals_area_pets1_opals_area_pets2_opals_balance_beam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opals',
            name='age_groups',
            field=models.CharField(default='', help_text='Comma-separated age groups (e.g. Infant,Toddler,Preschool)', max_length=255),
        ),
    ]
