# Generated by Django 5.0.1 on 2025-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_opals_age_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='opals',
            name='question24',
            field=models.CharField(blank=True, choices=[('level241', 'There is no multipurpose activity settings/lawn.'), ('level242', 'Multipurpose activity setting/lawn sufficient for only a few children to use together.'), ('level243', 'A medium size multipurpose activity setting/lawn large enough for at least half a class of children to use together.'), ('level244', 'A large multipurpose activity setting/lawn large enough for all children in a class to use together.')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question25',
            field=models.CharField(blank=True, choices=[('level251', 'There is no covered outdoor classroom/gathering place.'), ('level252', 'There is a covered outdoor classroom/gathering place large enough for only a small, informal group of children to use together with teacher.'), ('level253', 'There is a medium size covered outdoor classroom/gathering place large enough for at least half a class to use together with teacher.'), ('level254', 'There is a large covered outdoor classroom/gathering place large enough for all children in a class to use together with teacher.')], max_length=10, null=True),
        ),
    ]
