# Generated by Django 5.0.1 on 2025-04-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_opals_alphabet2_opals_alphabet3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opals',
            name='question51',
            field=models.CharField(blank=True, choices=[('level511', 'Little language is used, or language used is relevant to teachers perspectives rather than contingent on childrens activities and interests.'), ('level512', 'Teachers used some language relevant to childrens interests and activities; teachers language tends to be related to teachers interests, perspectives, or other duties. Verbalizations often restrict use of materials when guiding behaviors.'), ('level513', 'Teachers’ language related to childrens interests and activities occurs regularly; language related to teachers interests, perspectives, or other duties occurs for more than a few minutes. Verbalizations may restrict use of materials when guiding behaviors'), ('level514', 'Teachers’ language is consistently related to what children are playing with or looking at, what they are focused on or doing. Any restriction verbalization is related to safety/hazard.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question52',
            field=models.CharField(blank=True, choices=[('level521', 'Interactions are primarily for correction or instructions. The quantity of interactions may be very low. The teacher may be intrusive, dismissive or negative toward children. Children’s cues or bids are largely ignored'), ('level522', 'Some warm teacher-child interactions with children occur, and some instances of intrusion may occur. Teacher shows a positive response to a child’s bid or cue, but this does not occur often or only to a few select children.'), ('level523', 'Warm and positive teacher interactions occur several times and with different children. Most of children’s bids and cues are responded to or teachers occasionally initiate interactions with children who do not show bids/cues. Occasional instances of intrusion can occur.'), ('level524', 'Teachers consistently exhibit warm and positive interactions with various children. Children’s bids and cues are almost always responded to or teachers initiate interactions with children who do not show bids/cues. Any instances of intrusion are situationally appropriate.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question53',
            field=models.CharField(blank=True, choices=[('level531', 'Teachers inhibit/prohibit interactions with materials, or interrupt children’s interests or focus. Or teachers do not acknowledge and/or promote children’s persistence and learning.'), ('level532', 'Teachers offer or encourage children’s use of a few materials or acknowledge engagement using simple comments/questions.'), ('level533', 'Teachers are sensitive to children’s interests and may offer materials that interest children but may not promote extended exploration of materials or areas, or how to use or think about materials in different ways. Teachers ask some open-ended questions, but this is not consistent'), ('level534', 'Teachers may offer several materials, or alternative ways of using materials and/or follow children’s lead in exploring concepts and discoveries by asking open-ended questions, challenging their thinking/abilities, and scaffolding their learning.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question54',
            field=models.CharField(blank=True, choices=[('level541', 'Teachers are visually supervising and rarely physically engaged with children/materials.'), ('level542', 'Teachers are physically close to children but show limited physical engagement and/or modeling with them.'), ('level543', 'Teachers sometimes participate in shared play and reciprocal interactions (e.g., where teachers model inquisitiveness or exploration), but this participation does not last. They may offer or start some activities.'), ('level544', 'Teachers offer and start activities and continue to engage in the activities/play with extended interactions. Teachers are at children’s level and physically engaged by sharing activities and encouraging joint attention. Multiple examples of reciprocal/shared interactions (where teachers are modeling inquisitiveness or exploration) are observed between teachers and children.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question55',
            field=models.CharField(blank=True, choices=[('level551', 'Little support is provided for positive peer interactions and challenging situations'), ('level552', 'Some support for solving challenging situations. When support is given, it is usually vague (i.e., not giving problem-solving strategies) and/or not appropriate to the developmental level of the children'), ('level553', 'Some examples of support for positive peer interactions, but this is not consistent. Support is mostly given to children when there is conflict or challenging situations.'), ('level554', 'Teachers consistently support positive peer interaction and challenging situations if it is needed. Support and/or encouragement for positive peer interactions is given to children even if there is no conflict.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question56',
            field=models.CharField(blank=True, choices=[('level561', 'There is no natural environment or children are prohibited from engaging with the natural environment.'), ('level562', 'Teachers discourage interactions with the natural environment or do not encourage further exploration.'), ('level563', 'Teachers allow children to experience or interact with natural elements/environment. They minimally encourage and/or are passive about children’s engagement with the natural environment.'), ('level564', 'Teachers encourage children to be actively engaged with natural elements/environment by using their senses and skills to manipulate and explore it.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question57',
            field=models.CharField(blank=True, choices=[('level571', 'There are no children engaging with natural elements or the natural environment.'), ('level572', 'Child(ren) notice natural elements/environment but do not engage/spend time exploring it or are stopped from exploring further'), ('level573', 'Child(ren) display curiosity of and exploration with natural elements/environment for a short period of time'), ('level574', 'Child(ren) display curiosity of and exploration with the natural elements/environment for a sustained period of time.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question58',
            field=models.CharField(blank=True, choices=[('level581', 'There are no children engaging with the natural environment'), ('level582', 'One child engages with the natural environment'), ('level583', 'More than one but half or less of the children engage with the natural environment'), ('level584', 'More than half of the children engage with the natural environment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question59',
            field=models.CharField(blank=True, choices=[('level591', 'Children spend all their time in required teacher-led whole or small group activities. No or few options for child-directed activities exist'), ('level592', 'Children spend most of their time in the required teacher-led small/large group activities. Children have little time to engage in activities of their choice'), ('level593', 'Children spend almost half their time in teacher-led small/large group activities. Teacher-led activities do not take up the whole time. Children have half or more of their time to engage in activities of their choice'), ('level594', 'Children can choose their activities and direct their own learning. Small or large group activities are optional or short in duration when offered. Group activities may happen spontaneously.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opals',
            name='question60',
            field=models.CharField(blank=True, choices=[('level601', 'Climate is characterized by disrespect and harsh interactions, or teachers ignore children. There is no enthusiasm.'), ('level602', 'The climate is generally neutral with few instances of enthusiasm, affection, or respect shown between children and adults. There might be instances of sarcasm.'), ('level603', 'The climate is generally neutral with some periods of enthusiasm, affection, and respect shown by teachers and children'), ('level604', 'A consistently positive climate is demonstrated by sustained affection, enthusiastic, and respectful interactions that are just as likely to occur between any of the children and teachers')], max_length=20, null=True),
        ),
    ]
